-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dft is
port (
    real_sample_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_0_ce0 : OUT STD_LOGIC;
    real_sample_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_0_we0 : OUT STD_LOGIC;
    real_sample_0_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_0_ce1 : OUT STD_LOGIC;
    real_sample_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_0_we1 : OUT STD_LOGIC;
    real_sample_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_1_ce0 : OUT STD_LOGIC;
    real_sample_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_1_we0 : OUT STD_LOGIC;
    real_sample_1_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_1_ce1 : OUT STD_LOGIC;
    real_sample_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_1_we1 : OUT STD_LOGIC;
    real_sample_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_2_ce0 : OUT STD_LOGIC;
    real_sample_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_2_we0 : OUT STD_LOGIC;
    real_sample_2_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_2_ce1 : OUT STD_LOGIC;
    real_sample_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_2_we1 : OUT STD_LOGIC;
    real_sample_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_3_ce0 : OUT STD_LOGIC;
    real_sample_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_3_we0 : OUT STD_LOGIC;
    real_sample_3_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_3_ce1 : OUT STD_LOGIC;
    real_sample_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_3_we1 : OUT STD_LOGIC;
    real_sample_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_4_ce0 : OUT STD_LOGIC;
    real_sample_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_4_we0 : OUT STD_LOGIC;
    real_sample_4_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_4_ce1 : OUT STD_LOGIC;
    real_sample_4_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_4_we1 : OUT STD_LOGIC;
    real_sample_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_5_ce0 : OUT STD_LOGIC;
    real_sample_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_5_we0 : OUT STD_LOGIC;
    real_sample_5_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_5_ce1 : OUT STD_LOGIC;
    real_sample_5_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_5_we1 : OUT STD_LOGIC;
    real_sample_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_6_ce0 : OUT STD_LOGIC;
    real_sample_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_6_we0 : OUT STD_LOGIC;
    real_sample_6_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_6_ce1 : OUT STD_LOGIC;
    real_sample_6_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_6_we1 : OUT STD_LOGIC;
    real_sample_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_7_ce0 : OUT STD_LOGIC;
    real_sample_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_7_we0 : OUT STD_LOGIC;
    real_sample_7_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_7_ce1 : OUT STD_LOGIC;
    real_sample_7_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_7_we1 : OUT STD_LOGIC;
    real_sample_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_8_ce0 : OUT STD_LOGIC;
    real_sample_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_8_we0 : OUT STD_LOGIC;
    real_sample_8_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_8_ce1 : OUT STD_LOGIC;
    real_sample_8_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_8_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_8_we1 : OUT STD_LOGIC;
    real_sample_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_9_ce0 : OUT STD_LOGIC;
    real_sample_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_9_we0 : OUT STD_LOGIC;
    real_sample_9_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_9_ce1 : OUT STD_LOGIC;
    real_sample_9_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_9_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_9_we1 : OUT STD_LOGIC;
    real_sample_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_10_ce0 : OUT STD_LOGIC;
    real_sample_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_10_we0 : OUT STD_LOGIC;
    real_sample_10_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_10_ce1 : OUT STD_LOGIC;
    real_sample_10_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_10_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_10_we1 : OUT STD_LOGIC;
    real_sample_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_11_ce0 : OUT STD_LOGIC;
    real_sample_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_11_we0 : OUT STD_LOGIC;
    real_sample_11_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_11_ce1 : OUT STD_LOGIC;
    real_sample_11_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_11_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_11_we1 : OUT STD_LOGIC;
    real_sample_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_12_ce0 : OUT STD_LOGIC;
    real_sample_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_12_we0 : OUT STD_LOGIC;
    real_sample_12_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_12_ce1 : OUT STD_LOGIC;
    real_sample_12_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_12_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_12_we1 : OUT STD_LOGIC;
    real_sample_13_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_13_ce0 : OUT STD_LOGIC;
    real_sample_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_13_we0 : OUT STD_LOGIC;
    real_sample_13_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_13_ce1 : OUT STD_LOGIC;
    real_sample_13_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_13_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_13_we1 : OUT STD_LOGIC;
    real_sample_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_14_ce0 : OUT STD_LOGIC;
    real_sample_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_14_we0 : OUT STD_LOGIC;
    real_sample_14_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_14_ce1 : OUT STD_LOGIC;
    real_sample_14_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_14_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_14_we1 : OUT STD_LOGIC;
    real_sample_15_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_15_ce0 : OUT STD_LOGIC;
    real_sample_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_15_we0 : OUT STD_LOGIC;
    real_sample_15_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_sample_15_ce1 : OUT STD_LOGIC;
    real_sample_15_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_sample_15_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_15_we1 : OUT STD_LOGIC;
    imag_sample_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    imag_sample_ce0 : OUT STD_LOGIC;
    imag_sample_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    imag_sample_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_sample_we0 : OUT STD_LOGIC;
    sum_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    sum_r_ce0 : OUT STD_LOGIC;
    sum_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    sum_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    sum_r_we0 : OUT STD_LOGIC;
    sum_r_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    sum_r_ce1 : OUT STD_LOGIC;
    sum_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    sum_r_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    sum_r_we1 : OUT STD_LOGIC;
    sum_i_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    sum_i_ce0 : OUT STD_LOGIC;
    sum_i_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    sum_i_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    sum_i_we0 : OUT STD_LOGIC;
    sum_i_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    sum_i_ce1 : OUT STD_LOGIC;
    sum_i_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    sum_i_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    sum_i_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of dft is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dft_dft,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.512000,HLS_SYN_LAT=262151,HLS_SYN_TPT=262152,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=2652,HLS_SYN_LUT=2047,HLS_VERSION=2022_1}";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';

    signal Loop_top_loop_proc_U0_ap_start : STD_LOGIC;
    signal Loop_top_loop_proc_U0_ap_done : STD_LOGIC;
    signal Loop_top_loop_proc_U0_ap_continue : STD_LOGIC;
    signal Loop_top_loop_proc_U0_ap_idle : STD_LOGIC;
    signal Loop_top_loop_proc_U0_ap_ready : STD_LOGIC;
    signal Loop_top_loop_proc_U0_sum_r_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_top_loop_proc_U0_sum_r_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_sum_r_we0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_sum_r_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_top_loop_proc_U0_sum_i_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_top_loop_proc_U0_sum_i_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_sum_i_we0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_sum_i_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_0_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_1_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_2_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_3_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_4_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_4_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_5_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_5_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_6_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_6_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_7_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_7_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_8_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_8_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_9_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_9_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_10_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_10_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_11_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_11_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_12_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_12_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_13_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_13_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_14_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_14_ce0 : STD_LOGIC;
    signal Loop_top_loop_proc_U0_real_sample_15_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Loop_top_loop_proc_U0_real_sample_15_ce0 : STD_LOGIC;

    component dft_Loop_top_loop_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sum_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sum_r_ce0 : OUT STD_LOGIC;
        sum_r_we0 : OUT STD_LOGIC;
        sum_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_i_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        sum_i_ce0 : OUT STD_LOGIC;
        sum_i_we0 : OUT STD_LOGIC;
        sum_i_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        real_sample_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_0_ce0 : OUT STD_LOGIC;
        real_sample_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_1_ce0 : OUT STD_LOGIC;
        real_sample_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_2_ce0 : OUT STD_LOGIC;
        real_sample_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_3_ce0 : OUT STD_LOGIC;
        real_sample_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_4_ce0 : OUT STD_LOGIC;
        real_sample_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_5_ce0 : OUT STD_LOGIC;
        real_sample_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_6_ce0 : OUT STD_LOGIC;
        real_sample_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_7_ce0 : OUT STD_LOGIC;
        real_sample_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_8_ce0 : OUT STD_LOGIC;
        real_sample_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_9_ce0 : OUT STD_LOGIC;
        real_sample_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_10_ce0 : OUT STD_LOGIC;
        real_sample_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_11_ce0 : OUT STD_LOGIC;
        real_sample_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_12_ce0 : OUT STD_LOGIC;
        real_sample_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_13_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_13_ce0 : OUT STD_LOGIC;
        real_sample_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_14_ce0 : OUT STD_LOGIC;
        real_sample_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_15_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_sample_15_ce0 : OUT STD_LOGIC;
        real_sample_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    Loop_top_loop_proc_U0 : component dft_Loop_top_loop_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => Loop_top_loop_proc_U0_ap_start,
        ap_done => Loop_top_loop_proc_U0_ap_done,
        ap_continue => Loop_top_loop_proc_U0_ap_continue,
        ap_idle => Loop_top_loop_proc_U0_ap_idle,
        ap_ready => Loop_top_loop_proc_U0_ap_ready,
        sum_r_address0 => Loop_top_loop_proc_U0_sum_r_address0,
        sum_r_ce0 => Loop_top_loop_proc_U0_sum_r_ce0,
        sum_r_we0 => Loop_top_loop_proc_U0_sum_r_we0,
        sum_r_d0 => Loop_top_loop_proc_U0_sum_r_d0,
        sum_i_address0 => Loop_top_loop_proc_U0_sum_i_address0,
        sum_i_ce0 => Loop_top_loop_proc_U0_sum_i_ce0,
        sum_i_we0 => Loop_top_loop_proc_U0_sum_i_we0,
        sum_i_d0 => Loop_top_loop_proc_U0_sum_i_d0,
        real_sample_0_address0 => Loop_top_loop_proc_U0_real_sample_0_address0,
        real_sample_0_ce0 => Loop_top_loop_proc_U0_real_sample_0_ce0,
        real_sample_0_q0 => real_sample_0_q0,
        real_sample_1_address0 => Loop_top_loop_proc_U0_real_sample_1_address0,
        real_sample_1_ce0 => Loop_top_loop_proc_U0_real_sample_1_ce0,
        real_sample_1_q0 => real_sample_1_q0,
        real_sample_2_address0 => Loop_top_loop_proc_U0_real_sample_2_address0,
        real_sample_2_ce0 => Loop_top_loop_proc_U0_real_sample_2_ce0,
        real_sample_2_q0 => real_sample_2_q0,
        real_sample_3_address0 => Loop_top_loop_proc_U0_real_sample_3_address0,
        real_sample_3_ce0 => Loop_top_loop_proc_U0_real_sample_3_ce0,
        real_sample_3_q0 => real_sample_3_q0,
        real_sample_4_address0 => Loop_top_loop_proc_U0_real_sample_4_address0,
        real_sample_4_ce0 => Loop_top_loop_proc_U0_real_sample_4_ce0,
        real_sample_4_q0 => real_sample_4_q0,
        real_sample_5_address0 => Loop_top_loop_proc_U0_real_sample_5_address0,
        real_sample_5_ce0 => Loop_top_loop_proc_U0_real_sample_5_ce0,
        real_sample_5_q0 => real_sample_5_q0,
        real_sample_6_address0 => Loop_top_loop_proc_U0_real_sample_6_address0,
        real_sample_6_ce0 => Loop_top_loop_proc_U0_real_sample_6_ce0,
        real_sample_6_q0 => real_sample_6_q0,
        real_sample_7_address0 => Loop_top_loop_proc_U0_real_sample_7_address0,
        real_sample_7_ce0 => Loop_top_loop_proc_U0_real_sample_7_ce0,
        real_sample_7_q0 => real_sample_7_q0,
        real_sample_8_address0 => Loop_top_loop_proc_U0_real_sample_8_address0,
        real_sample_8_ce0 => Loop_top_loop_proc_U0_real_sample_8_ce0,
        real_sample_8_q0 => real_sample_8_q0,
        real_sample_9_address0 => Loop_top_loop_proc_U0_real_sample_9_address0,
        real_sample_9_ce0 => Loop_top_loop_proc_U0_real_sample_9_ce0,
        real_sample_9_q0 => real_sample_9_q0,
        real_sample_10_address0 => Loop_top_loop_proc_U0_real_sample_10_address0,
        real_sample_10_ce0 => Loop_top_loop_proc_U0_real_sample_10_ce0,
        real_sample_10_q0 => real_sample_10_q0,
        real_sample_11_address0 => Loop_top_loop_proc_U0_real_sample_11_address0,
        real_sample_11_ce0 => Loop_top_loop_proc_U0_real_sample_11_ce0,
        real_sample_11_q0 => real_sample_11_q0,
        real_sample_12_address0 => Loop_top_loop_proc_U0_real_sample_12_address0,
        real_sample_12_ce0 => Loop_top_loop_proc_U0_real_sample_12_ce0,
        real_sample_12_q0 => real_sample_12_q0,
        real_sample_13_address0 => Loop_top_loop_proc_U0_real_sample_13_address0,
        real_sample_13_ce0 => Loop_top_loop_proc_U0_real_sample_13_ce0,
        real_sample_13_q0 => real_sample_13_q0,
        real_sample_14_address0 => Loop_top_loop_proc_U0_real_sample_14_address0,
        real_sample_14_ce0 => Loop_top_loop_proc_U0_real_sample_14_ce0,
        real_sample_14_q0 => real_sample_14_q0,
        real_sample_15_address0 => Loop_top_loop_proc_U0_real_sample_15_address0,
        real_sample_15_ce0 => Loop_top_loop_proc_U0_real_sample_15_ce0,
        real_sample_15_q0 => real_sample_15_q0);




    Loop_top_loop_proc_U0_ap_continue <= ap_const_logic_1;
    Loop_top_loop_proc_U0_ap_start <= ap_start;
    ap_done <= Loop_top_loop_proc_U0_ap_done;
    ap_idle <= Loop_top_loop_proc_U0_ap_idle;
    ap_ready <= Loop_top_loop_proc_U0_ap_ready;
    imag_sample_address0 <= ap_const_lv8_0;
    imag_sample_ce0 <= ap_const_logic_0;
    imag_sample_d0 <= ap_const_lv32_0;
    imag_sample_we0 <= ap_const_logic_0;
    real_sample_0_address0 <= Loop_top_loop_proc_U0_real_sample_0_address0;
    real_sample_0_address1 <= ap_const_lv4_0;
    real_sample_0_ce0 <= Loop_top_loop_proc_U0_real_sample_0_ce0;
    real_sample_0_ce1 <= ap_const_logic_0;
    real_sample_0_d0 <= ap_const_lv32_0;
    real_sample_0_d1 <= ap_const_lv32_0;
    real_sample_0_we0 <= ap_const_logic_0;
    real_sample_0_we1 <= ap_const_logic_0;
    real_sample_10_address0 <= Loop_top_loop_proc_U0_real_sample_10_address0;
    real_sample_10_address1 <= ap_const_lv4_0;
    real_sample_10_ce0 <= Loop_top_loop_proc_U0_real_sample_10_ce0;
    real_sample_10_ce1 <= ap_const_logic_0;
    real_sample_10_d0 <= ap_const_lv32_0;
    real_sample_10_d1 <= ap_const_lv32_0;
    real_sample_10_we0 <= ap_const_logic_0;
    real_sample_10_we1 <= ap_const_logic_0;
    real_sample_11_address0 <= Loop_top_loop_proc_U0_real_sample_11_address0;
    real_sample_11_address1 <= ap_const_lv4_0;
    real_sample_11_ce0 <= Loop_top_loop_proc_U0_real_sample_11_ce0;
    real_sample_11_ce1 <= ap_const_logic_0;
    real_sample_11_d0 <= ap_const_lv32_0;
    real_sample_11_d1 <= ap_const_lv32_0;
    real_sample_11_we0 <= ap_const_logic_0;
    real_sample_11_we1 <= ap_const_logic_0;
    real_sample_12_address0 <= Loop_top_loop_proc_U0_real_sample_12_address0;
    real_sample_12_address1 <= ap_const_lv4_0;
    real_sample_12_ce0 <= Loop_top_loop_proc_U0_real_sample_12_ce0;
    real_sample_12_ce1 <= ap_const_logic_0;
    real_sample_12_d0 <= ap_const_lv32_0;
    real_sample_12_d1 <= ap_const_lv32_0;
    real_sample_12_we0 <= ap_const_logic_0;
    real_sample_12_we1 <= ap_const_logic_0;
    real_sample_13_address0 <= Loop_top_loop_proc_U0_real_sample_13_address0;
    real_sample_13_address1 <= ap_const_lv4_0;
    real_sample_13_ce0 <= Loop_top_loop_proc_U0_real_sample_13_ce0;
    real_sample_13_ce1 <= ap_const_logic_0;
    real_sample_13_d0 <= ap_const_lv32_0;
    real_sample_13_d1 <= ap_const_lv32_0;
    real_sample_13_we0 <= ap_const_logic_0;
    real_sample_13_we1 <= ap_const_logic_0;
    real_sample_14_address0 <= Loop_top_loop_proc_U0_real_sample_14_address0;
    real_sample_14_address1 <= ap_const_lv4_0;
    real_sample_14_ce0 <= Loop_top_loop_proc_U0_real_sample_14_ce0;
    real_sample_14_ce1 <= ap_const_logic_0;
    real_sample_14_d0 <= ap_const_lv32_0;
    real_sample_14_d1 <= ap_const_lv32_0;
    real_sample_14_we0 <= ap_const_logic_0;
    real_sample_14_we1 <= ap_const_logic_0;
    real_sample_15_address0 <= Loop_top_loop_proc_U0_real_sample_15_address0;
    real_sample_15_address1 <= ap_const_lv4_0;
    real_sample_15_ce0 <= Loop_top_loop_proc_U0_real_sample_15_ce0;
    real_sample_15_ce1 <= ap_const_logic_0;
    real_sample_15_d0 <= ap_const_lv32_0;
    real_sample_15_d1 <= ap_const_lv32_0;
    real_sample_15_we0 <= ap_const_logic_0;
    real_sample_15_we1 <= ap_const_logic_0;
    real_sample_1_address0 <= Loop_top_loop_proc_U0_real_sample_1_address0;
    real_sample_1_address1 <= ap_const_lv4_0;
    real_sample_1_ce0 <= Loop_top_loop_proc_U0_real_sample_1_ce0;
    real_sample_1_ce1 <= ap_const_logic_0;
    real_sample_1_d0 <= ap_const_lv32_0;
    real_sample_1_d1 <= ap_const_lv32_0;
    real_sample_1_we0 <= ap_const_logic_0;
    real_sample_1_we1 <= ap_const_logic_0;
    real_sample_2_address0 <= Loop_top_loop_proc_U0_real_sample_2_address0;
    real_sample_2_address1 <= ap_const_lv4_0;
    real_sample_2_ce0 <= Loop_top_loop_proc_U0_real_sample_2_ce0;
    real_sample_2_ce1 <= ap_const_logic_0;
    real_sample_2_d0 <= ap_const_lv32_0;
    real_sample_2_d1 <= ap_const_lv32_0;
    real_sample_2_we0 <= ap_const_logic_0;
    real_sample_2_we1 <= ap_const_logic_0;
    real_sample_3_address0 <= Loop_top_loop_proc_U0_real_sample_3_address0;
    real_sample_3_address1 <= ap_const_lv4_0;
    real_sample_3_ce0 <= Loop_top_loop_proc_U0_real_sample_3_ce0;
    real_sample_3_ce1 <= ap_const_logic_0;
    real_sample_3_d0 <= ap_const_lv32_0;
    real_sample_3_d1 <= ap_const_lv32_0;
    real_sample_3_we0 <= ap_const_logic_0;
    real_sample_3_we1 <= ap_const_logic_0;
    real_sample_4_address0 <= Loop_top_loop_proc_U0_real_sample_4_address0;
    real_sample_4_address1 <= ap_const_lv4_0;
    real_sample_4_ce0 <= Loop_top_loop_proc_U0_real_sample_4_ce0;
    real_sample_4_ce1 <= ap_const_logic_0;
    real_sample_4_d0 <= ap_const_lv32_0;
    real_sample_4_d1 <= ap_const_lv32_0;
    real_sample_4_we0 <= ap_const_logic_0;
    real_sample_4_we1 <= ap_const_logic_0;
    real_sample_5_address0 <= Loop_top_loop_proc_U0_real_sample_5_address0;
    real_sample_5_address1 <= ap_const_lv4_0;
    real_sample_5_ce0 <= Loop_top_loop_proc_U0_real_sample_5_ce0;
    real_sample_5_ce1 <= ap_const_logic_0;
    real_sample_5_d0 <= ap_const_lv32_0;
    real_sample_5_d1 <= ap_const_lv32_0;
    real_sample_5_we0 <= ap_const_logic_0;
    real_sample_5_we1 <= ap_const_logic_0;
    real_sample_6_address0 <= Loop_top_loop_proc_U0_real_sample_6_address0;
    real_sample_6_address1 <= ap_const_lv4_0;
    real_sample_6_ce0 <= Loop_top_loop_proc_U0_real_sample_6_ce0;
    real_sample_6_ce1 <= ap_const_logic_0;
    real_sample_6_d0 <= ap_const_lv32_0;
    real_sample_6_d1 <= ap_const_lv32_0;
    real_sample_6_we0 <= ap_const_logic_0;
    real_sample_6_we1 <= ap_const_logic_0;
    real_sample_7_address0 <= Loop_top_loop_proc_U0_real_sample_7_address0;
    real_sample_7_address1 <= ap_const_lv4_0;
    real_sample_7_ce0 <= Loop_top_loop_proc_U0_real_sample_7_ce0;
    real_sample_7_ce1 <= ap_const_logic_0;
    real_sample_7_d0 <= ap_const_lv32_0;
    real_sample_7_d1 <= ap_const_lv32_0;
    real_sample_7_we0 <= ap_const_logic_0;
    real_sample_7_we1 <= ap_const_logic_0;
    real_sample_8_address0 <= Loop_top_loop_proc_U0_real_sample_8_address0;
    real_sample_8_address1 <= ap_const_lv4_0;
    real_sample_8_ce0 <= Loop_top_loop_proc_U0_real_sample_8_ce0;
    real_sample_8_ce1 <= ap_const_logic_0;
    real_sample_8_d0 <= ap_const_lv32_0;
    real_sample_8_d1 <= ap_const_lv32_0;
    real_sample_8_we0 <= ap_const_logic_0;
    real_sample_8_we1 <= ap_const_logic_0;
    real_sample_9_address0 <= Loop_top_loop_proc_U0_real_sample_9_address0;
    real_sample_9_address1 <= ap_const_lv4_0;
    real_sample_9_ce0 <= Loop_top_loop_proc_U0_real_sample_9_ce0;
    real_sample_9_ce1 <= ap_const_logic_0;
    real_sample_9_d0 <= ap_const_lv32_0;
    real_sample_9_d1 <= ap_const_lv32_0;
    real_sample_9_we0 <= ap_const_logic_0;
    real_sample_9_we1 <= ap_const_logic_0;
    sum_i_address0 <= Loop_top_loop_proc_U0_sum_i_address0;
    sum_i_address1 <= ap_const_lv8_0;
    sum_i_ce0 <= Loop_top_loop_proc_U0_sum_i_ce0;
    sum_i_ce1 <= ap_const_logic_0;
    sum_i_d0 <= Loop_top_loop_proc_U0_sum_i_d0;
    sum_i_d1 <= ap_const_lv32_0;
    sum_i_we0 <= Loop_top_loop_proc_U0_sum_i_we0;
    sum_i_we1 <= ap_const_logic_0;
    sum_r_address0 <= Loop_top_loop_proc_U0_sum_r_address0;
    sum_r_address1 <= ap_const_lv8_0;
    sum_r_ce0 <= Loop_top_loop_proc_U0_sum_r_ce0;
    sum_r_ce1 <= ap_const_logic_0;
    sum_r_d0 <= Loop_top_loop_proc_U0_sum_r_d0;
    sum_r_d1 <= ap_const_lv32_0;
    sum_r_we0 <= Loop_top_loop_proc_U0_sum_r_we0;
    sum_r_we1 <= ap_const_logic_0;
end behav;
