// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dft_dft,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.512000,HLS_SYN_LAT=262151,HLS_SYN_TPT=262152,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=2652,HLS_SYN_LUT=2047,HLS_VERSION=2022_1}" *)

module dft (
        real_sample_0_address0,
        real_sample_0_ce0,
        real_sample_0_d0,
        real_sample_0_q0,
        real_sample_0_we0,
        real_sample_0_address1,
        real_sample_0_ce1,
        real_sample_0_d1,
        real_sample_0_q1,
        real_sample_0_we1,
        real_sample_1_address0,
        real_sample_1_ce0,
        real_sample_1_d0,
        real_sample_1_q0,
        real_sample_1_we0,
        real_sample_1_address1,
        real_sample_1_ce1,
        real_sample_1_d1,
        real_sample_1_q1,
        real_sample_1_we1,
        real_sample_2_address0,
        real_sample_2_ce0,
        real_sample_2_d0,
        real_sample_2_q0,
        real_sample_2_we0,
        real_sample_2_address1,
        real_sample_2_ce1,
        real_sample_2_d1,
        real_sample_2_q1,
        real_sample_2_we1,
        real_sample_3_address0,
        real_sample_3_ce0,
        real_sample_3_d0,
        real_sample_3_q0,
        real_sample_3_we0,
        real_sample_3_address1,
        real_sample_3_ce1,
        real_sample_3_d1,
        real_sample_3_q1,
        real_sample_3_we1,
        real_sample_4_address0,
        real_sample_4_ce0,
        real_sample_4_d0,
        real_sample_4_q0,
        real_sample_4_we0,
        real_sample_4_address1,
        real_sample_4_ce1,
        real_sample_4_d1,
        real_sample_4_q1,
        real_sample_4_we1,
        real_sample_5_address0,
        real_sample_5_ce0,
        real_sample_5_d0,
        real_sample_5_q0,
        real_sample_5_we0,
        real_sample_5_address1,
        real_sample_5_ce1,
        real_sample_5_d1,
        real_sample_5_q1,
        real_sample_5_we1,
        real_sample_6_address0,
        real_sample_6_ce0,
        real_sample_6_d0,
        real_sample_6_q0,
        real_sample_6_we0,
        real_sample_6_address1,
        real_sample_6_ce1,
        real_sample_6_d1,
        real_sample_6_q1,
        real_sample_6_we1,
        real_sample_7_address0,
        real_sample_7_ce0,
        real_sample_7_d0,
        real_sample_7_q0,
        real_sample_7_we0,
        real_sample_7_address1,
        real_sample_7_ce1,
        real_sample_7_d1,
        real_sample_7_q1,
        real_sample_7_we1,
        real_sample_8_address0,
        real_sample_8_ce0,
        real_sample_8_d0,
        real_sample_8_q0,
        real_sample_8_we0,
        real_sample_8_address1,
        real_sample_8_ce1,
        real_sample_8_d1,
        real_sample_8_q1,
        real_sample_8_we1,
        real_sample_9_address0,
        real_sample_9_ce0,
        real_sample_9_d0,
        real_sample_9_q0,
        real_sample_9_we0,
        real_sample_9_address1,
        real_sample_9_ce1,
        real_sample_9_d1,
        real_sample_9_q1,
        real_sample_9_we1,
        real_sample_10_address0,
        real_sample_10_ce0,
        real_sample_10_d0,
        real_sample_10_q0,
        real_sample_10_we0,
        real_sample_10_address1,
        real_sample_10_ce1,
        real_sample_10_d1,
        real_sample_10_q1,
        real_sample_10_we1,
        real_sample_11_address0,
        real_sample_11_ce0,
        real_sample_11_d0,
        real_sample_11_q0,
        real_sample_11_we0,
        real_sample_11_address1,
        real_sample_11_ce1,
        real_sample_11_d1,
        real_sample_11_q1,
        real_sample_11_we1,
        real_sample_12_address0,
        real_sample_12_ce0,
        real_sample_12_d0,
        real_sample_12_q0,
        real_sample_12_we0,
        real_sample_12_address1,
        real_sample_12_ce1,
        real_sample_12_d1,
        real_sample_12_q1,
        real_sample_12_we1,
        real_sample_13_address0,
        real_sample_13_ce0,
        real_sample_13_d0,
        real_sample_13_q0,
        real_sample_13_we0,
        real_sample_13_address1,
        real_sample_13_ce1,
        real_sample_13_d1,
        real_sample_13_q1,
        real_sample_13_we1,
        real_sample_14_address0,
        real_sample_14_ce0,
        real_sample_14_d0,
        real_sample_14_q0,
        real_sample_14_we0,
        real_sample_14_address1,
        real_sample_14_ce1,
        real_sample_14_d1,
        real_sample_14_q1,
        real_sample_14_we1,
        real_sample_15_address0,
        real_sample_15_ce0,
        real_sample_15_d0,
        real_sample_15_q0,
        real_sample_15_we0,
        real_sample_15_address1,
        real_sample_15_ce1,
        real_sample_15_d1,
        real_sample_15_q1,
        real_sample_15_we1,
        imag_sample_address0,
        imag_sample_ce0,
        imag_sample_d0,
        imag_sample_q0,
        imag_sample_we0,
        sum_r_address0,
        sum_r_ce0,
        sum_r_d0,
        sum_r_q0,
        sum_r_we0,
        sum_r_address1,
        sum_r_ce1,
        sum_r_d1,
        sum_r_q1,
        sum_r_we1,
        sum_i_address0,
        sum_i_ce0,
        sum_i_d0,
        sum_i_q0,
        sum_i_we0,
        sum_i_address1,
        sum_i_ce1,
        sum_i_d1,
        sum_i_q1,
        sum_i_we1,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


output  [3:0] real_sample_0_address0;
output   real_sample_0_ce0;
output  [31:0] real_sample_0_d0;
input  [31:0] real_sample_0_q0;
output   real_sample_0_we0;
output  [3:0] real_sample_0_address1;
output   real_sample_0_ce1;
output  [31:0] real_sample_0_d1;
input  [31:0] real_sample_0_q1;
output   real_sample_0_we1;
output  [3:0] real_sample_1_address0;
output   real_sample_1_ce0;
output  [31:0] real_sample_1_d0;
input  [31:0] real_sample_1_q0;
output   real_sample_1_we0;
output  [3:0] real_sample_1_address1;
output   real_sample_1_ce1;
output  [31:0] real_sample_1_d1;
input  [31:0] real_sample_1_q1;
output   real_sample_1_we1;
output  [3:0] real_sample_2_address0;
output   real_sample_2_ce0;
output  [31:0] real_sample_2_d0;
input  [31:0] real_sample_2_q0;
output   real_sample_2_we0;
output  [3:0] real_sample_2_address1;
output   real_sample_2_ce1;
output  [31:0] real_sample_2_d1;
input  [31:0] real_sample_2_q1;
output   real_sample_2_we1;
output  [3:0] real_sample_3_address0;
output   real_sample_3_ce0;
output  [31:0] real_sample_3_d0;
input  [31:0] real_sample_3_q0;
output   real_sample_3_we0;
output  [3:0] real_sample_3_address1;
output   real_sample_3_ce1;
output  [31:0] real_sample_3_d1;
input  [31:0] real_sample_3_q1;
output   real_sample_3_we1;
output  [3:0] real_sample_4_address0;
output   real_sample_4_ce0;
output  [31:0] real_sample_4_d0;
input  [31:0] real_sample_4_q0;
output   real_sample_4_we0;
output  [3:0] real_sample_4_address1;
output   real_sample_4_ce1;
output  [31:0] real_sample_4_d1;
input  [31:0] real_sample_4_q1;
output   real_sample_4_we1;
output  [3:0] real_sample_5_address0;
output   real_sample_5_ce0;
output  [31:0] real_sample_5_d0;
input  [31:0] real_sample_5_q0;
output   real_sample_5_we0;
output  [3:0] real_sample_5_address1;
output   real_sample_5_ce1;
output  [31:0] real_sample_5_d1;
input  [31:0] real_sample_5_q1;
output   real_sample_5_we1;
output  [3:0] real_sample_6_address0;
output   real_sample_6_ce0;
output  [31:0] real_sample_6_d0;
input  [31:0] real_sample_6_q0;
output   real_sample_6_we0;
output  [3:0] real_sample_6_address1;
output   real_sample_6_ce1;
output  [31:0] real_sample_6_d1;
input  [31:0] real_sample_6_q1;
output   real_sample_6_we1;
output  [3:0] real_sample_7_address0;
output   real_sample_7_ce0;
output  [31:0] real_sample_7_d0;
input  [31:0] real_sample_7_q0;
output   real_sample_7_we0;
output  [3:0] real_sample_7_address1;
output   real_sample_7_ce1;
output  [31:0] real_sample_7_d1;
input  [31:0] real_sample_7_q1;
output   real_sample_7_we1;
output  [3:0] real_sample_8_address0;
output   real_sample_8_ce0;
output  [31:0] real_sample_8_d0;
input  [31:0] real_sample_8_q0;
output   real_sample_8_we0;
output  [3:0] real_sample_8_address1;
output   real_sample_8_ce1;
output  [31:0] real_sample_8_d1;
input  [31:0] real_sample_8_q1;
output   real_sample_8_we1;
output  [3:0] real_sample_9_address0;
output   real_sample_9_ce0;
output  [31:0] real_sample_9_d0;
input  [31:0] real_sample_9_q0;
output   real_sample_9_we0;
output  [3:0] real_sample_9_address1;
output   real_sample_9_ce1;
output  [31:0] real_sample_9_d1;
input  [31:0] real_sample_9_q1;
output   real_sample_9_we1;
output  [3:0] real_sample_10_address0;
output   real_sample_10_ce0;
output  [31:0] real_sample_10_d0;
input  [31:0] real_sample_10_q0;
output   real_sample_10_we0;
output  [3:0] real_sample_10_address1;
output   real_sample_10_ce1;
output  [31:0] real_sample_10_d1;
input  [31:0] real_sample_10_q1;
output   real_sample_10_we1;
output  [3:0] real_sample_11_address0;
output   real_sample_11_ce0;
output  [31:0] real_sample_11_d0;
input  [31:0] real_sample_11_q0;
output   real_sample_11_we0;
output  [3:0] real_sample_11_address1;
output   real_sample_11_ce1;
output  [31:0] real_sample_11_d1;
input  [31:0] real_sample_11_q1;
output   real_sample_11_we1;
output  [3:0] real_sample_12_address0;
output   real_sample_12_ce0;
output  [31:0] real_sample_12_d0;
input  [31:0] real_sample_12_q0;
output   real_sample_12_we0;
output  [3:0] real_sample_12_address1;
output   real_sample_12_ce1;
output  [31:0] real_sample_12_d1;
input  [31:0] real_sample_12_q1;
output   real_sample_12_we1;
output  [3:0] real_sample_13_address0;
output   real_sample_13_ce0;
output  [31:0] real_sample_13_d0;
input  [31:0] real_sample_13_q0;
output   real_sample_13_we0;
output  [3:0] real_sample_13_address1;
output   real_sample_13_ce1;
output  [31:0] real_sample_13_d1;
input  [31:0] real_sample_13_q1;
output   real_sample_13_we1;
output  [3:0] real_sample_14_address0;
output   real_sample_14_ce0;
output  [31:0] real_sample_14_d0;
input  [31:0] real_sample_14_q0;
output   real_sample_14_we0;
output  [3:0] real_sample_14_address1;
output   real_sample_14_ce1;
output  [31:0] real_sample_14_d1;
input  [31:0] real_sample_14_q1;
output   real_sample_14_we1;
output  [3:0] real_sample_15_address0;
output   real_sample_15_ce0;
output  [31:0] real_sample_15_d0;
input  [31:0] real_sample_15_q0;
output   real_sample_15_we0;
output  [3:0] real_sample_15_address1;
output   real_sample_15_ce1;
output  [31:0] real_sample_15_d1;
input  [31:0] real_sample_15_q1;
output   real_sample_15_we1;
output  [7:0] imag_sample_address0;
output   imag_sample_ce0;
output  [31:0] imag_sample_d0;
input  [31:0] imag_sample_q0;
output   imag_sample_we0;
output  [7:0] sum_r_address0;
output   sum_r_ce0;
output  [31:0] sum_r_d0;
input  [31:0] sum_r_q0;
output   sum_r_we0;
output  [7:0] sum_r_address1;
output   sum_r_ce1;
output  [31:0] sum_r_d1;
input  [31:0] sum_r_q1;
output   sum_r_we1;
output  [7:0] sum_i_address0;
output   sum_i_ce0;
output  [31:0] sum_i_d0;
input  [31:0] sum_i_q0;
output   sum_i_we0;
output  [7:0] sum_i_address1;
output   sum_i_ce1;
output  [31:0] sum_i_d1;
input  [31:0] sum_i_q1;
output   sum_i_we1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Loop_top_loop_proc_U0_ap_start;
wire    Loop_top_loop_proc_U0_ap_done;
wire    Loop_top_loop_proc_U0_ap_continue;
wire    Loop_top_loop_proc_U0_ap_idle;
wire    Loop_top_loop_proc_U0_ap_ready;
wire   [7:0] Loop_top_loop_proc_U0_sum_r_address0;
wire    Loop_top_loop_proc_U0_sum_r_ce0;
wire    Loop_top_loop_proc_U0_sum_r_we0;
wire   [31:0] Loop_top_loop_proc_U0_sum_r_d0;
wire   [7:0] Loop_top_loop_proc_U0_sum_i_address0;
wire    Loop_top_loop_proc_U0_sum_i_ce0;
wire    Loop_top_loop_proc_U0_sum_i_we0;
wire   [31:0] Loop_top_loop_proc_U0_sum_i_d0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_0_address0;
wire    Loop_top_loop_proc_U0_real_sample_0_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_1_address0;
wire    Loop_top_loop_proc_U0_real_sample_1_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_2_address0;
wire    Loop_top_loop_proc_U0_real_sample_2_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_3_address0;
wire    Loop_top_loop_proc_U0_real_sample_3_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_4_address0;
wire    Loop_top_loop_proc_U0_real_sample_4_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_5_address0;
wire    Loop_top_loop_proc_U0_real_sample_5_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_6_address0;
wire    Loop_top_loop_proc_U0_real_sample_6_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_7_address0;
wire    Loop_top_loop_proc_U0_real_sample_7_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_8_address0;
wire    Loop_top_loop_proc_U0_real_sample_8_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_9_address0;
wire    Loop_top_loop_proc_U0_real_sample_9_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_10_address0;
wire    Loop_top_loop_proc_U0_real_sample_10_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_11_address0;
wire    Loop_top_loop_proc_U0_real_sample_11_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_12_address0;
wire    Loop_top_loop_proc_U0_real_sample_12_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_13_address0;
wire    Loop_top_loop_proc_U0_real_sample_13_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_14_address0;
wire    Loop_top_loop_proc_U0_real_sample_14_ce0;
wire   [3:0] Loop_top_loop_proc_U0_real_sample_15_address0;
wire    Loop_top_loop_proc_U0_real_sample_15_ce0;

dft_Loop_top_loop_proc Loop_top_loop_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_top_loop_proc_U0_ap_start),
    .ap_done(Loop_top_loop_proc_U0_ap_done),
    .ap_continue(Loop_top_loop_proc_U0_ap_continue),
    .ap_idle(Loop_top_loop_proc_U0_ap_idle),
    .ap_ready(Loop_top_loop_proc_U0_ap_ready),
    .sum_r_address0(Loop_top_loop_proc_U0_sum_r_address0),
    .sum_r_ce0(Loop_top_loop_proc_U0_sum_r_ce0),
    .sum_r_we0(Loop_top_loop_proc_U0_sum_r_we0),
    .sum_r_d0(Loop_top_loop_proc_U0_sum_r_d0),
    .sum_i_address0(Loop_top_loop_proc_U0_sum_i_address0),
    .sum_i_ce0(Loop_top_loop_proc_U0_sum_i_ce0),
    .sum_i_we0(Loop_top_loop_proc_U0_sum_i_we0),
    .sum_i_d0(Loop_top_loop_proc_U0_sum_i_d0),
    .real_sample_0_address0(Loop_top_loop_proc_U0_real_sample_0_address0),
    .real_sample_0_ce0(Loop_top_loop_proc_U0_real_sample_0_ce0),
    .real_sample_0_q0(real_sample_0_q0),
    .real_sample_1_address0(Loop_top_loop_proc_U0_real_sample_1_address0),
    .real_sample_1_ce0(Loop_top_loop_proc_U0_real_sample_1_ce0),
    .real_sample_1_q0(real_sample_1_q0),
    .real_sample_2_address0(Loop_top_loop_proc_U0_real_sample_2_address0),
    .real_sample_2_ce0(Loop_top_loop_proc_U0_real_sample_2_ce0),
    .real_sample_2_q0(real_sample_2_q0),
    .real_sample_3_address0(Loop_top_loop_proc_U0_real_sample_3_address0),
    .real_sample_3_ce0(Loop_top_loop_proc_U0_real_sample_3_ce0),
    .real_sample_3_q0(real_sample_3_q0),
    .real_sample_4_address0(Loop_top_loop_proc_U0_real_sample_4_address0),
    .real_sample_4_ce0(Loop_top_loop_proc_U0_real_sample_4_ce0),
    .real_sample_4_q0(real_sample_4_q0),
    .real_sample_5_address0(Loop_top_loop_proc_U0_real_sample_5_address0),
    .real_sample_5_ce0(Loop_top_loop_proc_U0_real_sample_5_ce0),
    .real_sample_5_q0(real_sample_5_q0),
    .real_sample_6_address0(Loop_top_loop_proc_U0_real_sample_6_address0),
    .real_sample_6_ce0(Loop_top_loop_proc_U0_real_sample_6_ce0),
    .real_sample_6_q0(real_sample_6_q0),
    .real_sample_7_address0(Loop_top_loop_proc_U0_real_sample_7_address0),
    .real_sample_7_ce0(Loop_top_loop_proc_U0_real_sample_7_ce0),
    .real_sample_7_q0(real_sample_7_q0),
    .real_sample_8_address0(Loop_top_loop_proc_U0_real_sample_8_address0),
    .real_sample_8_ce0(Loop_top_loop_proc_U0_real_sample_8_ce0),
    .real_sample_8_q0(real_sample_8_q0),
    .real_sample_9_address0(Loop_top_loop_proc_U0_real_sample_9_address0),
    .real_sample_9_ce0(Loop_top_loop_proc_U0_real_sample_9_ce0),
    .real_sample_9_q0(real_sample_9_q0),
    .real_sample_10_address0(Loop_top_loop_proc_U0_real_sample_10_address0),
    .real_sample_10_ce0(Loop_top_loop_proc_U0_real_sample_10_ce0),
    .real_sample_10_q0(real_sample_10_q0),
    .real_sample_11_address0(Loop_top_loop_proc_U0_real_sample_11_address0),
    .real_sample_11_ce0(Loop_top_loop_proc_U0_real_sample_11_ce0),
    .real_sample_11_q0(real_sample_11_q0),
    .real_sample_12_address0(Loop_top_loop_proc_U0_real_sample_12_address0),
    .real_sample_12_ce0(Loop_top_loop_proc_U0_real_sample_12_ce0),
    .real_sample_12_q0(real_sample_12_q0),
    .real_sample_13_address0(Loop_top_loop_proc_U0_real_sample_13_address0),
    .real_sample_13_ce0(Loop_top_loop_proc_U0_real_sample_13_ce0),
    .real_sample_13_q0(real_sample_13_q0),
    .real_sample_14_address0(Loop_top_loop_proc_U0_real_sample_14_address0),
    .real_sample_14_ce0(Loop_top_loop_proc_U0_real_sample_14_ce0),
    .real_sample_14_q0(real_sample_14_q0),
    .real_sample_15_address0(Loop_top_loop_proc_U0_real_sample_15_address0),
    .real_sample_15_ce0(Loop_top_loop_proc_U0_real_sample_15_ce0),
    .real_sample_15_q0(real_sample_15_q0)
);

assign Loop_top_loop_proc_U0_ap_continue = 1'b1;

assign Loop_top_loop_proc_U0_ap_start = ap_start;

assign ap_done = Loop_top_loop_proc_U0_ap_done;

assign ap_idle = Loop_top_loop_proc_U0_ap_idle;

assign ap_ready = Loop_top_loop_proc_U0_ap_ready;

assign imag_sample_address0 = 8'd0;

assign imag_sample_ce0 = 1'b0;

assign imag_sample_d0 = 32'd0;

assign imag_sample_we0 = 1'b0;

assign real_sample_0_address0 = Loop_top_loop_proc_U0_real_sample_0_address0;

assign real_sample_0_address1 = 4'd0;

assign real_sample_0_ce0 = Loop_top_loop_proc_U0_real_sample_0_ce0;

assign real_sample_0_ce1 = 1'b0;

assign real_sample_0_d0 = 32'd0;

assign real_sample_0_d1 = 32'd0;

assign real_sample_0_we0 = 1'b0;

assign real_sample_0_we1 = 1'b0;

assign real_sample_10_address0 = Loop_top_loop_proc_U0_real_sample_10_address0;

assign real_sample_10_address1 = 4'd0;

assign real_sample_10_ce0 = Loop_top_loop_proc_U0_real_sample_10_ce0;

assign real_sample_10_ce1 = 1'b0;

assign real_sample_10_d0 = 32'd0;

assign real_sample_10_d1 = 32'd0;

assign real_sample_10_we0 = 1'b0;

assign real_sample_10_we1 = 1'b0;

assign real_sample_11_address0 = Loop_top_loop_proc_U0_real_sample_11_address0;

assign real_sample_11_address1 = 4'd0;

assign real_sample_11_ce0 = Loop_top_loop_proc_U0_real_sample_11_ce0;

assign real_sample_11_ce1 = 1'b0;

assign real_sample_11_d0 = 32'd0;

assign real_sample_11_d1 = 32'd0;

assign real_sample_11_we0 = 1'b0;

assign real_sample_11_we1 = 1'b0;

assign real_sample_12_address0 = Loop_top_loop_proc_U0_real_sample_12_address0;

assign real_sample_12_address1 = 4'd0;

assign real_sample_12_ce0 = Loop_top_loop_proc_U0_real_sample_12_ce0;

assign real_sample_12_ce1 = 1'b0;

assign real_sample_12_d0 = 32'd0;

assign real_sample_12_d1 = 32'd0;

assign real_sample_12_we0 = 1'b0;

assign real_sample_12_we1 = 1'b0;

assign real_sample_13_address0 = Loop_top_loop_proc_U0_real_sample_13_address0;

assign real_sample_13_address1 = 4'd0;

assign real_sample_13_ce0 = Loop_top_loop_proc_U0_real_sample_13_ce0;

assign real_sample_13_ce1 = 1'b0;

assign real_sample_13_d0 = 32'd0;

assign real_sample_13_d1 = 32'd0;

assign real_sample_13_we0 = 1'b0;

assign real_sample_13_we1 = 1'b0;

assign real_sample_14_address0 = Loop_top_loop_proc_U0_real_sample_14_address0;

assign real_sample_14_address1 = 4'd0;

assign real_sample_14_ce0 = Loop_top_loop_proc_U0_real_sample_14_ce0;

assign real_sample_14_ce1 = 1'b0;

assign real_sample_14_d0 = 32'd0;

assign real_sample_14_d1 = 32'd0;

assign real_sample_14_we0 = 1'b0;

assign real_sample_14_we1 = 1'b0;

assign real_sample_15_address0 = Loop_top_loop_proc_U0_real_sample_15_address0;

assign real_sample_15_address1 = 4'd0;

assign real_sample_15_ce0 = Loop_top_loop_proc_U0_real_sample_15_ce0;

assign real_sample_15_ce1 = 1'b0;

assign real_sample_15_d0 = 32'd0;

assign real_sample_15_d1 = 32'd0;

assign real_sample_15_we0 = 1'b0;

assign real_sample_15_we1 = 1'b0;

assign real_sample_1_address0 = Loop_top_loop_proc_U0_real_sample_1_address0;

assign real_sample_1_address1 = 4'd0;

assign real_sample_1_ce0 = Loop_top_loop_proc_U0_real_sample_1_ce0;

assign real_sample_1_ce1 = 1'b0;

assign real_sample_1_d0 = 32'd0;

assign real_sample_1_d1 = 32'd0;

assign real_sample_1_we0 = 1'b0;

assign real_sample_1_we1 = 1'b0;

assign real_sample_2_address0 = Loop_top_loop_proc_U0_real_sample_2_address0;

assign real_sample_2_address1 = 4'd0;

assign real_sample_2_ce0 = Loop_top_loop_proc_U0_real_sample_2_ce0;

assign real_sample_2_ce1 = 1'b0;

assign real_sample_2_d0 = 32'd0;

assign real_sample_2_d1 = 32'd0;

assign real_sample_2_we0 = 1'b0;

assign real_sample_2_we1 = 1'b0;

assign real_sample_3_address0 = Loop_top_loop_proc_U0_real_sample_3_address0;

assign real_sample_3_address1 = 4'd0;

assign real_sample_3_ce0 = Loop_top_loop_proc_U0_real_sample_3_ce0;

assign real_sample_3_ce1 = 1'b0;

assign real_sample_3_d0 = 32'd0;

assign real_sample_3_d1 = 32'd0;

assign real_sample_3_we0 = 1'b0;

assign real_sample_3_we1 = 1'b0;

assign real_sample_4_address0 = Loop_top_loop_proc_U0_real_sample_4_address0;

assign real_sample_4_address1 = 4'd0;

assign real_sample_4_ce0 = Loop_top_loop_proc_U0_real_sample_4_ce0;

assign real_sample_4_ce1 = 1'b0;

assign real_sample_4_d0 = 32'd0;

assign real_sample_4_d1 = 32'd0;

assign real_sample_4_we0 = 1'b0;

assign real_sample_4_we1 = 1'b0;

assign real_sample_5_address0 = Loop_top_loop_proc_U0_real_sample_5_address0;

assign real_sample_5_address1 = 4'd0;

assign real_sample_5_ce0 = Loop_top_loop_proc_U0_real_sample_5_ce0;

assign real_sample_5_ce1 = 1'b0;

assign real_sample_5_d0 = 32'd0;

assign real_sample_5_d1 = 32'd0;

assign real_sample_5_we0 = 1'b0;

assign real_sample_5_we1 = 1'b0;

assign real_sample_6_address0 = Loop_top_loop_proc_U0_real_sample_6_address0;

assign real_sample_6_address1 = 4'd0;

assign real_sample_6_ce0 = Loop_top_loop_proc_U0_real_sample_6_ce0;

assign real_sample_6_ce1 = 1'b0;

assign real_sample_6_d0 = 32'd0;

assign real_sample_6_d1 = 32'd0;

assign real_sample_6_we0 = 1'b0;

assign real_sample_6_we1 = 1'b0;

assign real_sample_7_address0 = Loop_top_loop_proc_U0_real_sample_7_address0;

assign real_sample_7_address1 = 4'd0;

assign real_sample_7_ce0 = Loop_top_loop_proc_U0_real_sample_7_ce0;

assign real_sample_7_ce1 = 1'b0;

assign real_sample_7_d0 = 32'd0;

assign real_sample_7_d1 = 32'd0;

assign real_sample_7_we0 = 1'b0;

assign real_sample_7_we1 = 1'b0;

assign real_sample_8_address0 = Loop_top_loop_proc_U0_real_sample_8_address0;

assign real_sample_8_address1 = 4'd0;

assign real_sample_8_ce0 = Loop_top_loop_proc_U0_real_sample_8_ce0;

assign real_sample_8_ce1 = 1'b0;

assign real_sample_8_d0 = 32'd0;

assign real_sample_8_d1 = 32'd0;

assign real_sample_8_we0 = 1'b0;

assign real_sample_8_we1 = 1'b0;

assign real_sample_9_address0 = Loop_top_loop_proc_U0_real_sample_9_address0;

assign real_sample_9_address1 = 4'd0;

assign real_sample_9_ce0 = Loop_top_loop_proc_U0_real_sample_9_ce0;

assign real_sample_9_ce1 = 1'b0;

assign real_sample_9_d0 = 32'd0;

assign real_sample_9_d1 = 32'd0;

assign real_sample_9_we0 = 1'b0;

assign real_sample_9_we1 = 1'b0;

assign sum_i_address0 = Loop_top_loop_proc_U0_sum_i_address0;

assign sum_i_address1 = 8'd0;

assign sum_i_ce0 = Loop_top_loop_proc_U0_sum_i_ce0;

assign sum_i_ce1 = 1'b0;

assign sum_i_d0 = Loop_top_loop_proc_U0_sum_i_d0;

assign sum_i_d1 = 32'd0;

assign sum_i_we0 = Loop_top_loop_proc_U0_sum_i_we0;

assign sum_i_we1 = 1'b0;

assign sum_r_address0 = Loop_top_loop_proc_U0_sum_r_address0;

assign sum_r_address1 = 8'd0;

assign sum_r_ce0 = Loop_top_loop_proc_U0_sum_r_ce0;

assign sum_r_ce1 = 1'b0;

assign sum_r_d0 = Loop_top_loop_proc_U0_sum_r_d0;

assign sum_r_d1 = 32'd0;

assign sum_r_we0 = Loop_top_loop_proc_U0_sum_r_we0;

assign sum_r_we1 = 1'b0;

endmodule //dft
