// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dft_dft,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=74,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=7621,HLS_SYN_LUT=10592,HLS_VERSION=2022_1}" *)

module dft (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        real_sample_address0,
        real_sample_ce0,
        real_sample_we0,
        real_sample_d0,
        real_sample_q0,
        real_sample_address1,
        real_sample_ce1,
        real_sample_q1,
        imag_sample_address0,
        imag_sample_ce0,
        imag_sample_we0,
        imag_sample_d0
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] real_sample_address0;
output   real_sample_ce0;
output   real_sample_we0;
output  [31:0] real_sample_d0;
input  [31:0] real_sample_q0;
output  [2:0] real_sample_address1;
output   real_sample_ce1;
input  [31:0] real_sample_q1;
output  [2:0] imag_sample_address0;
output   imag_sample_ce0;
output   imag_sample_we0;
output  [31:0] imag_sample_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] real_sample_address0;
reg real_sample_ce0;
reg real_sample_we0;
reg[2:0] real_sample_address1;
reg real_sample_ce1;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] reg_181;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state9;
wire   [31:0] bitcast_ln14_fu_185_p1;
reg   [31:0] bitcast_ln14_reg_226;
wire    ap_CS_fsm_state3;
wire   [31:0] grp_fu_176_p2;
reg   [31:0] mul_reg_232;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state8;
reg   [31:0] real_sample_load_2_reg_252;
wire    ap_CS_fsm_state10;
reg   [31:0] real_sample_load_3_reg_257;
wire   [31:0] grp_fu_166_p2;
reg   [31:0] add_reg_272;
wire    ap_CS_fsm_state11;
reg   [31:0] real_sample_load_4_reg_277;
reg   [31:0] real_sample_load_5_reg_282;
wire   [31:0] grp_fu_171_p2;
reg   [31:0] add1_reg_297;
wire   [31:0] bitcast_ln14_1_fu_190_p1;
reg   [31:0] bitcast_ln14_1_reg_302;
wire    ap_CS_fsm_state12;
wire   [31:0] bitcast_ln14_2_fu_195_p1;
reg   [31:0] bitcast_ln14_2_reg_307;
wire   [31:0] bitcast_ln14_3_fu_199_p1;
reg   [31:0] bitcast_ln14_3_reg_312;
wire   [31:0] bitcast_ln14_4_fu_203_p1;
reg   [31:0] bitcast_ln14_4_reg_317;
wire   [31:0] bitcast_ln14_5_fu_207_p1;
reg   [31:0] bitcast_ln14_5_reg_322;
wire   [31:0] bitcast_ln14_6_fu_211_p1;
reg   [31:0] bitcast_ln14_6_reg_327;
wire   [31:0] bitcast_ln14_7_fu_216_p1;
reg   [31:0] bitcast_ln14_7_reg_332;
reg   [2:0] sum_r_address0;
reg    sum_r_ce0;
reg    sum_r_we0;
wire   [31:0] sum_r_q0;
reg   [2:0] sum_i_address0;
reg    sum_i_ce0;
reg    sum_i_we0;
wire   [31:0] sum_i_q0;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_start;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_done;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_idle;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_ready;
wire   [2:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_we0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_d0;
wire   [2:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_we0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_d0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_din0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_din1;
wire   [1:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_opcode;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_ce;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_din0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_din1;
wire   [1:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_opcode;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_ce;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_176_p_din0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_176_p_din1;
wire    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_176_p_ce;
wire    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_start;
wire    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_done;
wire    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_idle;
wire    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_ready;
wire   [2:0] grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_r_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_r_ce0;
wire   [2:0] grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_we0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_d0;
wire   [2:0] grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_i_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_i_ce0;
wire   [2:0] grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_address0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_ce0;
wire    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_we0;
wire   [31:0] grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_d0;
reg    grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_start_reg;
wire    ap_CS_fsm_state13;
reg    grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg   [31:0] grp_fu_166_p0;
reg   [31:0] grp_fu_166_p1;
wire    ap_CS_fsm_state7;
reg   [31:0] grp_fu_171_p0;
reg   [31:0] grp_fu_171_p1;
reg   [31:0] grp_fu_176_p0;
reg   [31:0] grp_fu_176_p1;
reg    grp_fu_166_ce;
reg    grp_fu_171_ce;
reg    grp_fu_176_ce;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_start_reg = 1'b0;
#0 grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_start_reg = 1'b0;
end

dft_sum_r_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
sum_r_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_r_address0),
    .ce0(sum_r_ce0),
    .we0(sum_r_we0),
    .d0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_d0),
    .q0(sum_r_q0)
);

dft_sum_r_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
sum_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_i_address0),
    .ce0(sum_i_ce0),
    .we0(sum_i_we0),
    .d0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_d0),
    .q0(sum_i_q0)
);

dft_dft_Pipeline_VITIS_LOOP_10_1 grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_start),
    .ap_done(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_done),
    .ap_idle(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_idle),
    .ap_ready(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_ready),
    .sum_r_address0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_address0),
    .sum_r_ce0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_ce0),
    .sum_r_we0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_we0),
    .sum_r_d0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_d0),
    .bitcast_ln14_1(bitcast_ln14_1_reg_302),
    .add(add_reg_272),
    .bitcast_ln14_2(bitcast_ln14_2_reg_307),
    .bitcast_ln14_3(bitcast_ln14_3_reg_312),
    .bitcast_ln14_4(bitcast_ln14_4_reg_317),
    .bitcast_ln14_5(bitcast_ln14_5_reg_322),
    .bitcast_ln14_6(bitcast_ln14_6_reg_327),
    .bitcast_ln14_7(bitcast_ln14_7_reg_332),
    .sum_i_address0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_address0),
    .sum_i_ce0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_ce0),
    .sum_i_we0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_we0),
    .sum_i_d0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_d0),
    .add1(add1_reg_297),
    .grp_fu_166_p_din0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_din0),
    .grp_fu_166_p_din1(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_din1),
    .grp_fu_166_p_opcode(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_opcode),
    .grp_fu_166_p_dout0(grp_fu_166_p2),
    .grp_fu_166_p_ce(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_ce),
    .grp_fu_171_p_din0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_din0),
    .grp_fu_171_p_din1(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_din1),
    .grp_fu_171_p_opcode(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_opcode),
    .grp_fu_171_p_dout0(grp_fu_171_p2),
    .grp_fu_171_p_ce(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_ce),
    .grp_fu_176_p_din0(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_176_p_din0),
    .grp_fu_176_p_din1(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_176_p_din1),
    .grp_fu_176_p_dout0(grp_fu_176_p2),
    .grp_fu_176_p_ce(grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_176_p_ce)
);

dft_dft_Pipeline_VITIS_LOOP_21_4 grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_start),
    .ap_done(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_done),
    .ap_idle(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_idle),
    .ap_ready(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_ready),
    .sum_r_address0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_r_address0),
    .sum_r_ce0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_r_ce0),
    .sum_r_q0(sum_r_q0),
    .real_sample_address0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_address0),
    .real_sample_ce0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_ce0),
    .real_sample_we0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_we0),
    .real_sample_d0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_d0),
    .sum_i_address0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_i_address0),
    .sum_i_ce0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_i_ce0),
    .sum_i_q0(sum_i_q0),
    .imag_sample_address0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_address0),
    .imag_sample_ce0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_ce0),
    .imag_sample_we0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_we0),
    .imag_sample_d0(grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_d0)
);

dft_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_166_p0),
    .din1(grp_fu_166_p1),
    .ce(grp_fu_166_ce),
    .dout(grp_fu_166_p2)
);

dft_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_171_p0),
    .din1(grp_fu_171_p1),
    .ce(grp_fu_171_ce),
    .dout(grp_fu_171_p2)
);

dft_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_176_p0),
    .din1(grp_fu_176_p1),
    .ce(grp_fu_176_ce),
    .dout(grp_fu_176_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_start_reg <= 1'b1;
        end else if ((grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_ready == 1'b1)) begin
            grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_start_reg <= 1'b1;
        end else if ((grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_ready == 1'b1)) begin
            grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add1_reg_297 <= grp_fu_171_p2;
        add_reg_272 <= grp_fu_166_p2;
        real_sample_load_4_reg_277 <= real_sample_q0;
        real_sample_load_5_reg_282 <= real_sample_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        bitcast_ln14_1_reg_302 <= bitcast_ln14_1_fu_190_p1;
        bitcast_ln14_2_reg_307 <= bitcast_ln14_2_fu_195_p1;
        bitcast_ln14_3_reg_312 <= bitcast_ln14_3_fu_199_p1;
        bitcast_ln14_4_reg_317 <= bitcast_ln14_4_fu_203_p1;
        bitcast_ln14_5_reg_322 <= bitcast_ln14_5_fu_207_p1;
        bitcast_ln14_6_reg_327 <= bitcast_ln14_6_fu_211_p1;
        bitcast_ln14_7_reg_332 <= bitcast_ln14_7_fu_216_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bitcast_ln14_reg_226 <= bitcast_ln14_fu_185_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mul_reg_232 <= grp_fu_176_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        real_sample_load_2_reg_252 <= real_sample_q1;
        real_sample_load_3_reg_257 <= real_sample_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_181 <= real_sample_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_166_ce = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_ce;
    end else begin
        grp_fu_166_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_166_p0 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_166_p0 = bitcast_ln14_reg_226;
    end else begin
        grp_fu_166_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_166_p1 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_166_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_166_p1 = 32'd0;
    end else begin
        grp_fu_166_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_171_ce = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_ce;
    end else begin
        grp_fu_171_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_171_p0 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_171_p0 = mul_reg_232;
    end else begin
        grp_fu_171_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_171_p1 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_171_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_171_p1 = 32'd0;
    end else begin
        grp_fu_171_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_176_ce = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_176_p_ce;
    end else begin
        grp_fu_176_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_176_p0 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_176_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_176_p0 = bitcast_ln14_fu_185_p1;
    end else begin
        grp_fu_176_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_176_p1 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_grp_fu_176_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_176_p1 = 32'd2147483648;
    end else begin
        grp_fu_176_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        real_sample_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        real_sample_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        real_sample_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        real_sample_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        real_sample_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        real_sample_address0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_address0;
    end else begin
        real_sample_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        real_sample_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        real_sample_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        real_sample_address1 = 64'd2;
    end else begin
        real_sample_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state11) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        real_sample_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        real_sample_ce0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_ce0;
    end else begin
        real_sample_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state11))) begin
        real_sample_ce1 = 1'b1;
    end else begin
        real_sample_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        real_sample_we0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_we0;
    end else begin
        real_sample_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        sum_i_address0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_i_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        sum_i_address0 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_address0;
    end else begin
        sum_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        sum_i_ce0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_i_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        sum_i_ce0 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_ce0;
    end else begin
        sum_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        sum_i_we0 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_i_we0;
    end else begin
        sum_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        sum_r_address0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        sum_r_address0 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_address0;
    end else begin
        sum_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        sum_r_ce0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_sum_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        sum_r_ce0 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_ce0;
    end else begin
        sum_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        sum_r_we0 = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_sum_r_we0;
    end else begin
        sum_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln14_1_fu_190_p1 = reg_181;

assign bitcast_ln14_2_fu_195_p1 = real_sample_load_2_reg_252;

assign bitcast_ln14_3_fu_199_p1 = real_sample_load_3_reg_257;

assign bitcast_ln14_4_fu_203_p1 = real_sample_load_4_reg_277;

assign bitcast_ln14_5_fu_207_p1 = real_sample_load_5_reg_282;

assign bitcast_ln14_6_fu_211_p1 = real_sample_q0;

assign bitcast_ln14_7_fu_216_p1 = real_sample_q1;

assign bitcast_ln14_fu_185_p1 = reg_181;

assign grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_start = grp_dft_Pipeline_VITIS_LOOP_10_1_fu_137_ap_start_reg;

assign grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_start = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_ap_start_reg;

assign imag_sample_address0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_address0;

assign imag_sample_ce0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_ce0;

assign imag_sample_d0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_d0;

assign imag_sample_we0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_imag_sample_we0;

assign real_sample_d0 = grp_dft_Pipeline_VITIS_LOOP_21_4_fu_156_real_sample_d0;

endmodule //dft
