-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dft is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    real_sample_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    real_sample_ce0 : OUT STD_LOGIC;
    real_sample_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_sample_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    imag_sample_ce0 : OUT STD_LOGIC;
    imag_sample_we0 : OUT STD_LOGIC;
    imag_sample_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    imag_sample_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_sample_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    imag_sample_ce1 : OUT STD_LOGIC;
    imag_sample_we1 : OUT STD_LOGIC;
    imag_sample_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    imag_sample_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    sum_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    sum_r_ce0 : OUT STD_LOGIC;
    sum_r_we0 : OUT STD_LOGIC;
    sum_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    sum_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    sum_i_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    sum_i_ce0 : OUT STD_LOGIC;
    sum_i_we0 : OUT STD_LOGIC;
    sum_i_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    sum_i_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of dft is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dft_dft,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=791553,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=894,HLS_SYN_LUT=1319,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sum_r_addr_reg_194 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln12_fu_119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln18_fu_137_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln18_reg_199 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_i_addr_reg_205 : STD_LOGIC_VECTOR (7 downto 0);
    signal bitcast_ln16_fu_146_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln16_reg_210 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal bitcast_ln24_fu_159_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln24_reg_215 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_start : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_done : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_idle : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_ready : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_real_sample_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_real_sample_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_p_out_ap_vld : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_ce : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_ce : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_start : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_done : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_idle : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_ready : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_real_sample_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_real_sample_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_p_out_ap_vld : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_ce : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_ce : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln12_fu_131_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal k_fu_52 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln12_fu_125_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_fu_220_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_220_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_220_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_220_ce : STD_LOGIC;
    signal grp_fu_224_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_224_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_224_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_224_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dft_dft_Pipeline_VITIS_LOOP_14_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bitcast_ln16 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        real_sample_ce0 : OUT STD_LOGIC;
        real_sample_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        trunc_ln18_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        grp_fu_220_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_220_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_220_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_220_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_220_p_ce : OUT STD_LOGIC;
        grp_fu_224_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_224_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_224_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_224_p_ce : OUT STD_LOGIC );
    end component;


    component dft_dft_Pipeline_VITIS_LOOP_22_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bitcast_ln24 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        real_sample_ce0 : OUT STD_LOGIC;
        real_sample_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        trunc_ln18_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        grp_fu_220_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_220_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_220_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_220_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_220_p_ce : OUT STD_LOGIC;
        grp_fu_224_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_224_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_224_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_224_p_ce : OUT STD_LOGIC );
    end component;


    component dft_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dft_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89 : component dft_dft_Pipeline_VITIS_LOOP_14_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_start,
        ap_done => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_done,
        ap_idle => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_idle,
        ap_ready => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_ready,
        bitcast_ln16 => bitcast_ln16_reg_210,
        real_sample_address0 => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_real_sample_address0,
        real_sample_ce0 => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_real_sample_ce0,
        real_sample_q0 => real_sample_q0,
        trunc_ln18_1 => trunc_ln18_reg_199,
        p_out => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_p_out,
        p_out_ap_vld => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_p_out_ap_vld,
        grp_fu_220_p_din0 => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_din0,
        grp_fu_220_p_din1 => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_din1,
        grp_fu_220_p_opcode => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_opcode,
        grp_fu_220_p_dout0 => grp_fu_220_p2,
        grp_fu_220_p_ce => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_ce,
        grp_fu_224_p_din0 => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_din0,
        grp_fu_224_p_din1 => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_din1,
        grp_fu_224_p_dout0 => grp_fu_224_p2,
        grp_fu_224_p_ce => grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_ce);

    grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100 : component dft_dft_Pipeline_VITIS_LOOP_22_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_start,
        ap_done => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_done,
        ap_idle => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_idle,
        ap_ready => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_ready,
        bitcast_ln24 => bitcast_ln24_reg_215,
        real_sample_address0 => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_real_sample_address0,
        real_sample_ce0 => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_real_sample_ce0,
        real_sample_q0 => real_sample_q0,
        trunc_ln18_1 => trunc_ln18_reg_199,
        p_out => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_p_out,
        p_out_ap_vld => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_p_out_ap_vld,
        grp_fu_220_p_din0 => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_din0,
        grp_fu_220_p_din1 => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_din1,
        grp_fu_220_p_opcode => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_opcode,
        grp_fu_220_p_dout0 => grp_fu_220_p2,
        grp_fu_220_p_ce => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_ce,
        grp_fu_224_p_din0 => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_din0,
        grp_fu_224_p_din1 => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_din1,
        grp_fu_224_p_dout0 => grp_fu_224_p2,
        grp_fu_224_p_ce => grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_ce);

    fadd_32ns_32ns_32_5_full_dsp_1_U15 : component dft_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_220_p0,
        din1 => grp_fu_220_p1,
        ce => grp_fu_220_ce,
        dout => grp_fu_220_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U16 : component dft_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_224_p0,
        din1 => grp_fu_224_p1,
        ce => grp_fu_224_ce,
        dout => grp_fu_224_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_ready = ap_const_logic_1)) then 
                    grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_ready = ap_const_logic_1)) then 
                    grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    k_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                k_fu_52 <= ap_const_lv9_0;
            elsif (((icmp_ln12_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                k_fu_52 <= add_ln12_fu_125_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                bitcast_ln16_reg_210 <= bitcast_ln16_fu_146_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                bitcast_ln24_reg_215 <= bitcast_ln24_fu_159_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln12_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                sum_i_addr_reg_205 <= zext_ln12_fu_131_p1(8 - 1 downto 0);
                sum_r_addr_reg_194 <= zext_ln12_fu_131_p1(8 - 1 downto 0);
                trunc_ln18_reg_199 <= trunc_ln18_fu_137_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln12_fu_119_p2, grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_done, grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln12_fu_119_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln12_fu_125_p2 <= std_logic_vector(unsigned(k_fu_52) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_done)
    begin
        if ((grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_done)
    begin
        if ((grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln12_fu_119_p2)
    begin
        if (((icmp_ln12_fu_119_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln12_fu_119_p2)
    begin
        if (((icmp_ln12_fu_119_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln16_fu_146_p1 <= sum_r_q0;
    bitcast_ln24_fu_159_p1 <= sum_i_q0;
    grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_start <= grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_start_reg;
    grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_start <= grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_ap_start_reg;

    grp_fu_220_ce_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_ce, grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_ce, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_220_ce <= grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_220_ce <= grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_ce;
        else 
            grp_fu_220_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_220_p0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_din0, grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_220_p0 <= grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_220_p0 <= grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_din0;
        else 
            grp_fu_220_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_220_p1_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_din1, grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_220_p1 <= grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_220_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_220_p1 <= grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_220_p_din1;
        else 
            grp_fu_220_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_224_ce_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_ce, grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_ce, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_224_ce <= grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_224_ce <= grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_ce;
        else 
            grp_fu_224_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_224_p0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_din0, grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_224_p0 <= grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_224_p0 <= grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_din0;
        else 
            grp_fu_224_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_224_p1_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_din1, grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_224_p1 <= grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_grp_fu_224_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_224_p1 <= grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_grp_fu_224_p_din1;
        else 
            grp_fu_224_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln12_fu_119_p2 <= "1" when (k_fu_52 = ap_const_lv9_100) else "0";
    imag_sample_address0 <= ap_const_lv8_0;
    imag_sample_address1 <= ap_const_lv8_0;
    imag_sample_ce0 <= ap_const_logic_0;
    imag_sample_ce1 <= ap_const_logic_0;
    imag_sample_d0 <= ap_const_lv32_0;
    imag_sample_d1 <= ap_const_lv32_0;
    imag_sample_we0 <= ap_const_logic_0;
    imag_sample_we1 <= ap_const_logic_0;

    real_sample_address0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_real_sample_address0, grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_real_sample_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            real_sample_address0 <= grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_real_sample_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            real_sample_address0 <= grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_real_sample_address0;
        else 
            real_sample_address0 <= "XXXXXXXX";
        end if; 
    end process;


    real_sample_ce0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_real_sample_ce0, grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_real_sample_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            real_sample_ce0 <= grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_real_sample_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            real_sample_ce0 <= grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_real_sample_ce0;
        else 
            real_sample_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    sum_i_address0 <= sum_i_addr_reg_205;

    sum_i_ce0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            sum_i_ce0 <= ap_const_logic_1;
        else 
            sum_i_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    sum_i_d0 <= grp_dft_Pipeline_VITIS_LOOP_22_3_fu_100_p_out;

    sum_i_we0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            sum_i_we0 <= ap_const_logic_1;
        else 
            sum_i_we0 <= ap_const_logic_0;
        end if; 
    end process;


    sum_r_address0_assign_proc : process(sum_r_addr_reg_194, ap_CS_fsm_state2, ap_CS_fsm_state5, zext_ln12_fu_131_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            sum_r_address0 <= sum_r_addr_reg_194;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            sum_r_address0 <= zext_ln12_fu_131_p1(8 - 1 downto 0);
        else 
            sum_r_address0 <= "XXXXXXXX";
        end if; 
    end process;


    sum_r_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            sum_r_ce0 <= ap_const_logic_1;
        else 
            sum_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    sum_r_d0 <= grp_dft_Pipeline_VITIS_LOOP_14_2_fu_89_p_out;

    sum_r_we0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            sum_r_we0 <= ap_const_logic_1;
        else 
            sum_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln18_fu_137_p1 <= k_fu_52(8 - 1 downto 0);
    zext_ln12_fu_131_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_fu_52),64));
end behav;
